source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ZAlertView_Example' do
  pod "ZAlertView", :path => "../"
end

target 'ZAlertView_Tests' do
  pod "ZAlertView", :path => "../"

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
